# Generated by Django 4.2.1 on 2023-05-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_artist_artist_name_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
