# Generated by Django 4.2.1 on 2023-05-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
