# Generated by Django 4.2.1 on 2023-05-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_likes2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='likes2',
        ),
    ]
